#pragma once

#include <string>

std::string frame_symbolic_data =
    "length: 20\n"
    "interval: 48\n"
    "layers:\n"
    "  - length: 20\n"
    "    begin: 5\n"
    "    end: 15\n"
    "    grid:\n"
    "      length: 20\n"
    "      rows: 4\n"
    "      origin: 0\n"
    "      orientation: 2\n"
    "    chroma:\n"
    "      length: 20\n"
    "      hue_shift: -1\n"
    "      source: aquamarine\n"
    "      target: salmon\n"
    "  - length: 20\n"
    "    begin: 5\n"
    "    end: 15\n"
    "    grid:\n"
    "      length: 20\n"
    "      rows: 4\n"
    "      origin: 0\n"
    "      orientation: 2\n"
    "    chroma:\n"
    "      length: 20\n"
    "      hue_shift: -1\n"
    "      source: aquamarine\n"
    "      target: salmon\n"
    "  - length: 20\n"
    "    begin: 5\n"
    "    end: 15\n"
    "    grid:\n"
    "      length: 20\n"
    "      rows: 4\n"
    "      origin: 0\n"
    "      orientation: 2\n"
    "    chroma:\n"
    "      length: 20\n"
    "      hue_shift: -1\n"
    "      source: aquamarine\n"
    "      target: salmon\n"
    "  - length: 20\n"
    "    begin: 5\n"
    "    end: 15\n"
    "    grid:\n"
    "      length: 20\n"
    "      rows: 4\n"
    "      origin: 0\n"
    "      orientation: 2\n"
    "    chroma:\n"
    "      length: 20\n"
    "      hue_shift: -1\n"
    "      source: aquamarine\n"
    "      target: salmon\n"
    "  - length: 16\n"
    "    begin: 5\n"
    "    end: 15\n"
    "    grid:\n"
    "      length: 20\n"
    "      rows: 4\n"
    "      origin: 0\n"
    "      orientation: 2\n"
    "    chroma:\n"
    "      length: 20\n"
    "      hue_shift: -1\n"
    "      source: aquamarine\n"
    "      target: salmon\n";