
#include "palette_builder.h"

namespace glow
{
#ifdef BUILD_PALETTE
  std::map<std::string, PaletteColor> palette = {
      {"red", {"", Color(0xed0a3f)}},
      {"maroon", {"", Color(0xc32148)}},
      {"scarlet", {"", Color(0xfd0e35)}},
      {"brick red", {"", Color(0xc62d42)}},
      {"english vermilion", {"", Color(0xcc474b)}},
      {"madder lake", {"", Color(0xcc3336)}},
      {"permanent geranium lake", {"", Color(0xe12c2c)}},
      {"maximum red", {"", Color(0xd92121)}},
      {"indian red", {"", Color(0xb94e48)}},
      {"orange-red", {"", Color(0xff5349)}},
      {"sunset orange", {"", Color(0xfe4c40)}},
      {"bittersweet", {"", Color(0xfe6f5e)}},
      {"dark venetian red", {"", Color(0xb33b24)}},
      {"venetian red", {"", Color(0xcc553d)}},
      {"light venetian red", {"", Color(0xe6735c)}},
      {"vivid tangerine", {"", Color(0xff9980)}},
      {"middle red", {"", Color(0xe58e73)}},
      {"burnt orange", {"", Color(0xff7f49)}},
      {"red-orange", {"", Color(0xff681f)}},
      {"orange", {"", Color(0xff8833)}},
      {"macaroni and cheese", {"", Color(0xffb97b)}},
      {"middle yellow red", {"", Color(0xecb176)}},
      {"mango tango", {"", Color(0xe77200)}},
      {"yellow-orange", {"", Color(0xffae42)}},
      {"maximum yellow red", {"", Color(0xf2ba49)}},
      {"banana mania", {"", Color(0xfbe7b2)}},
      {"maize", {"", Color(0xf2c649)}},
      {"orange-yellow", {"", Color(0xf8d568)}},
      {"goldenrod", {"", Color(0xfcd667)}},
      {"dandelion", {"", Color(0xfed85d)}},
      {"yellow", {"", Color(0xfbe870)}},
      {"green-yellow", {"", Color(0xf1e788)}},
      {"middle yellow", {"", Color(0xffeb00)}},
      {"olive green", {"", Color(0xb5b35c)}},
      {"spring green", {"", Color(0xecebbd)}},
      {"maximum yellow", {"", Color(0xfafa37)}},
      {"canary", {"", Color(0xffff99)}},
      {"lemon yellow", {"", Color(0xffff9f)}},
      {"maximum green yellow", {"", Color(0xd9e650)}},
      {"middle green yellow", {"", Color(0xacbf60)}},
      {"inchworm", {"", Color(0xafe313)}},
      {"light chrome green", {"", Color(0xbee64b)}},
      {"yellow-green", {"", Color(0xc5e17a)}},
      {"maximum green", {"", Color(0x5e8c31)}},
      {"asparagus", {"", Color(0x7ba05b)}},
      {"granny smith apple", {"", Color(0x9de093)}},
      {"fern", {"", Color(0x63b76c)}},
      {"middle green", {"", Color(0x4d8c57)}},
      {"green", {"", Color(0x3aa655)}},
      {"medium chrome green", {"", Color(0x6ca67c)}},
      {"forest green", {"", Color(0x5fa777)}},
      {"sea green", {"", Color(0x93dfb8)}},
      {"shamrock", {"", Color(0x33cc99)}},
      {"mountain meadow", {"", Color(0x1ab385)}},
      {"jungle green", {"", Color(0x29ab87)}},
      {"caribbean green", {"", Color(0x00cc99)}},
      {"tropical rain forest", {"", Color(0x00755e)}},
      {"middle blue green", {"", Color(0x8dd9cc)}},
      {"pine green", {"", Color(0x01786f)}},
      {"maximum blue green", {"", Color(0x30bfbf)}},
      {"robin's egg blue", {"", Color(0x00cccc)}},
      {"teal blue", {"", Color(0x008080)}},
      {"light blue", {"", Color(0x8fd8d8)}},
      {"aquamarine", {"", Color(0x95e0e8)}},
      {"turquoise blue", {"", Color(0x6cdae7)}},
      {"outer space", {"", Color(0x2d383a)}},
      {"sky blue", {"", Color(0x76d7ea)}},
      {"middle blue", {"", Color(0x7ed4e6)}},
      {"blue-green", {"", Color(0x0095b7)}},
      {"pacific blue", {"", Color(0x009dc4)}},
      {"cerulean", {"", Color(0x02a4d3)}},
      {"maximum blue", {"", Color(0x47abcc)}},
      {"blue (i)", {"", Color(0x4997d0)}},
      {"cerulean blue", {"", Color(0x339acc)}},
      {"cornflower", {"", Color(0x93ccea)}},
      {"green-blue", {"", Color(0x2887c8)}},
      {"midnight blue", {"", Color(0x00468c)}},
      {"navy blue", {"", Color(0x0066cc)}},
      {"denim", {"", Color(0x1560bd)}},
      {"blue (iii)", {"", Color(0x0066ff)}},
      {"cadet blue", {"", Color(0xa9b2c3)}},
      {"periwinkle", {"", Color(0xc3cde6)}},
      {"blue (ii)", {"", Color(0x4570e6)}},
      {"wild blue yonder", {"", Color(0x7a89b8)}},
      {"indigo", {"", Color(0x4f69c6)}},
      {"manatee", {"", Color(0x8d90a1)}},
      {"cobalt blue", {"", Color(0x8c90c8)}},
      {"celestial blue", {"", Color(0x7070cc)}},
      {"blue bell", {"", Color(0x9999cc)}},
      {"maximum blue purple", {"", Color(0xacace6)}},
      {"violet-blue", {"", Color(0x766ec8)}},
      {"blue-violet", {"", Color(0x6456b7)}},
      {"ultramarine blue", {"", Color(0x3f26bf)}},
      {"middle blue purple", {"", Color(0x8b72be)}},
      {"purple heart", {"", Color(0x652dc1)}},
      {"royal purple", {"", Color(0x6b3fa0)}},
      {"violet (ii)", {"", Color(0x8359a3)}},
      {"medium violet", {"", Color(0x8f47b3)}},
      {"wisteria", {"", Color(0xc9a0dc)}},
      {"lavender (i)", {"", Color(0xbf8fcc)}},
      {"vivid violet", {"", Color(0x803790)}},
      {"maximum purple", {"", Color(0x733380)}},
      {"purple mountains' majesty", {"", Color(0xd6aedd)}},
      {"fuchsia", {"", Color(0xc154c1)}},
      {"pink flamingo", {"", Color(0xfc74fd)}},
      {"violet (i)", {"", Color(0x732e6c)}},
      {"brilliant rose", {"", Color(0xe667ce)}},
      {"orchid", {"", Color(0xe29cd2)}},
      {"plum", {"", Color(0x8e3179)}},
      {"medium rose", {"", Color(0xd96cbe)}},
      {"thistle", {"", Color(0xebb0d7)}},
      {"mulberry", {"", Color(0xc8509b)}},
      {"red-violet", {"", Color(0xbb3385)}},
      {"middle purple", {"", Color(0xd982b5)}},
      {"maximum red purple", {"", Color(0xa63a79)}},
      {"jazzberry jam", {"", Color(0xa50b5e)}},
      {"eggplant", {"", Color(0x614051)}},
      {"magenta", {"", Color(0xf653a6)}},
      {"cerise", {"", Color(0xda3287)}},
      {"wild strawberry", {"", Color(0xff3399)}},
      {"lavender (ii)", {"", Color(0xfbaed2)}},
      {"cotton candy", {"", Color(0xffb7d5)}},
      {"carnation pink", {"", Color(0xffa6c9)}},
      {"violet-red", {"", Color(0xf7468a)}},
      {"razzmatazz", {"", Color(0xe30b5c)}},
      {"pig pink", {"", Color(0xfdd7e4)}},
      {"carmine", {"", Color(0xe62e6b)}},
      {"blush", {"", Color(0xdb5079)}},
      {"tickle me pink", {"", Color(0xfc80a5)}},
      {"mauvelous", {"", Color(0xf091a9)}},
      {"salmon", {"", Color(0xff91a4)}},
      {"middle red purple", {"", Color(0xa55353)}},
      {"mahogany", {"", Color(0xca3435)}},
      {"melon", {"", Color(0xfebaad)}},
      {"pink sherbert", {"", Color(0xf7a38e)}},
      {"burnt sienna", {"", Color(0xe97451)}},
      {"brown", {"", Color(0xaf593e)}},
      {"sepia", {"", Color(0x9e5b40)}},
      {"fuzzy wuzzy", {"", Color(0x87421f)}},
      {"beaver", {"", Color(0x926f5b)}},
      {"tumbleweed", {"", Color(0xdea681)}},
      {"raw sienna", {"", Color(0xd27d46)}},
      {"van dyke brown", {"", Color(0x664228)}},
      {"tan", {"", Color(0xd99a6c)}},
      {"desert sand", {"", Color(0xedc9af)}},
      {"peach", {"", Color(0xffcba4)}},
      {"burnt umber", {"", Color(0x805533)}},
      {"apricot", {"", Color(0xfdd5b1)}},
      {"almond", {"", Color(0xeed9c4)}},
      {"raw umber", {"", Color(0x665233)}},
      {"shadow", {"", Color(0x837050)}},
      {"raw sienna (i)", {"", Color(0xe6bc5c)}},
      {"timberwolf", {"", Color(0xd9d6cf)}},
      {"gold (i)", {"", Color(0x92926e)}},
      {"gold (ii)", {"", Color(0xe6be8a)}},
      {"silver", {"", Color(0xc9c0bb)}},
      {"copper", {"", Color(0xda8a67)}},
      {"antique brass", {"", Color(0xc88a65)}},
      {"black", {"", Color(0x000000)}},
      {"charcoal gray", {"", Color(0x736a62)}},
      {"gray", {"", Color(0x8b8680)}},
      {"blue-gray", {"", Color(0xc8c8cd)}},
  };
  // #else
  // std::map<std::string, Palette> palette{};

  std::map<std::string, PaletteColor> &
  build_palette()
  {
    float hue{}, saturation{}, value{};
    for (auto item : palette)
    {
      item.second.name = item.first;
      item.second.hsv.from_rgb(item.second.rgb);
      item.second.hsv.to_color_wheel(hue, saturation, value);
      item.second.hsv.from_color_wheel(hue, saturation, value);
      palette[item.first] = item.second;
    }
    return palette;
  }
#endif

}